default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root
  # password: password
  # host: db

development:
  <<: *default
  database: Brass_app_development

test:
  <<: *default
  database: Brass_app_test

production:
  <<: *default
  # magia用の設定
  # database: clcn6p8nv0014bxquelh15x15
  # username: clcn6p8nt0012bxqu33htaeh5
  # password: <%= ENV['BRASS_APP_DATABASE_PASSWORD'] %>
  # url: <%= ENV['DATABASE_URL'] %>

  # Heroku用の設定
  url: <%= ENV['DATABASE_URL'] %>